### ISSUE TITLE
VCF to GVF

### ISSUE THREAD

**Issue by bsaylor23** [Test-Blu/GVF_to_VCF#1]
Hi I've seen your code linked in a couple of forms about converting VCF to GVF. When I tested your code I could only figure out how to go the other way around (from GVF to VCF) can it do both conversion?

**Comment by AlirezaDostmohammadi** [comment]
Dear [bsaylor23](https://github.com/bsaylor23)

This script is designed to convert GVF to VCF, not vice versa. However, with some modifications to the code, you can adapt it for VCF to GVF conversion.

**Comment by AlirezaDostmohammadi** [comment]
If you have any other questions, please reopen this issue.
